"""Domain entities for Family Car Agent."""

from datetime import datetime

from pydantic import BaseModel, Field

from shared.models.enums import AgeGroup, MappingState, Relationship


class RoleAttributes(BaseModel):
    """Runtime role attributes determining permissions and response style."""

    driver: bool = False
    age_group: AgeGroup = AgeGroup.ADULT
    relationship: Relationship = Relationship.FAMILY
    account_owner: bool = False


class VehicleProfile(BaseModel):
    """Registered family member profile stored in DynamoDB."""

    vehicle_id: str
    actor_id: str
    name: str
    age_group: AgeGroup
    relationship: Relationship
    account_owner: bool = False
    default_seat_channel: int | None = None
    preferences_summary: str | None = None


class TripSession(BaseModel):
    """Active trip session stored in Valkey."""

    trip_id: str
    vehicle_id: str
    started_at: datetime
    state: MappingState = MappingState.IDLE
    seat_occupancy: dict[int, str | None] = Field(default_factory=dict)
    speaker_mappings: dict[str, str] = Field(default_factory=dict)
    driver_actor_id: str | None = None


class Utterance(BaseModel):
    """A single utterance from a speaker."""

    utterance_id: str
    trip_id: str
    actor_id: str
    spk_label: str
    transcript: str
    timestamp: datetime
    seat_channel: int
    confidence: float = 1.0


class ResponseStyle(BaseModel):
    """Persona-specific response style configuration."""

    tone: str = "efficient"
    verbosity: str = "high"
    speech_rate: float = 1.0
    honorific: str = "casual"
    confirmation_required: bool = False


class PolicyDecision(BaseModel):
    """Result of a CEDAR policy evaluation."""

    allowed: bool
    rule_id: str | None = None
    reason: str | None = None
    actor_id: str
    tool_name: str
    context: dict = Field(default_factory=dict)


class AgentResponse(BaseModel):
    """Response generated by the agent for a specific actor."""

    response_id: str
    trip_id: str
    actor_id: str
    text: str
    tool_used: str | None = None
    tool_result: dict | None = None
    policy_decision: PolicyDecision | None = None
    persona_style: ResponseStyle = Field(default_factory=ResponseStyle)
    latency_ms: int = 0


class ConcurrentBuffer(BaseModel):
    """Buffer for concurrent speech detection (500ms window)."""

    trip_id: str
    buffer_start: datetime
    utterances: list[Utterance] = Field(default_factory=list)
    window_ms: int = 500


class Pattern(BaseModel):
    """Extracted preference pattern from trip utterances."""

    category: str
    key: str
    value: str
    confidence_delta: float = 0.1


class ReflectionResult(BaseModel):
    """Result of reflection agent processing for one actor."""

    trip_id: str
    actor_id: str
    patterns: list[Pattern] = Field(default_factory=list)
    promoted_to_ltm: bool = False
